# Generated by Django 2.2 on 2020-02-19 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_shows', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='show',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app_shows.Show'),
            preserve_default=False,
        ),
    ]
